version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.7
    - 1.32.8
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.3.0
    - 10.4.1
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.7.1
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: ember-qunit
    versions:
    - 5.1.3
  - dependency-name: "@ember/test-helpers"
    versions:
    - 2.2.0
    - 2.2.1
  - dependency-name: ember-cli-page-object
    versions:
    - 1.17.6
  - dependency-name: handlebars
    versions:
    - 4.7.6
  commit-message:
    prefix: chore
    include: scope
